name: 'File Regex Replace 2023'
description: 'Allows you to perform a regex replace in your repository files'
branding:
  icon: 'box'  
  color: 'green'
inputs:
  regex:
    description: 'regex to apply(regex)'
    required: true
  flags:
    description: 'flags of the regex'
    default: 'g'
    required: false
  replacement:
    description: 'replacement string'
    default: "$1"
    required: true
  include:
    description: 'Files to be replaced(regex)'
    default: '.*'
    required: false
  exclude:
    description: 'Files not to be replaced(regex)'
    default: '.^'
    required: false
  encoding:
    description: 'String file encoding'
    default: 'utf8'
    required: false
  path:
    description: 'Path to the folder to be replaced'
    default: '.'
    required: false
outputs:
  value:
    description: 'regex replaced in your repository files'
runs:
  using: 'node20'
  main: 'index.js'
